# Generated by Django 5.1.3 on 2024-11-29 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventcategory_event_price_event_category_eventimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
